In [1]:
import pandas as pd
from keras.src.backend.jax.math import top_k

In [2]:
books = pd.read_csv("books_with_categories.csv")

In [3]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NonFiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NonFiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NonFiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,NonFiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [5]:
from transformers import pipeline
classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base",top_k = None,device = 0)
classifier("I love this!")

Device set to use cpu

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528684265911579},
  {'label': 'neutral', 'score': 0.005764583125710487},
  {'label': 'anger', 'score': 0.004419783595949411},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.0016119909705594182},
  {'label': 'fear', 'score': 0.00041385277290828526}]]

In [6]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [7]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [8]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296020984649658},
 {'label': 'neutral', 'score': 0.14038600027561188},
 {'label': 'fear', 'score': 0.06816228479146957},
 {'label': 'joy', 'score': 0.04794260859489441},
 {'label': 'anger', 'score': 0.009156366810202599},
 {'label': 'disgust', 'score': 0.0026284765917807817},
 {'label': 'sadness', 'score': 0.002122163539752364}]

In [11]:
import numpy as np


def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction,key=lambda x:x["label"])
        for index,label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label : np.max(scores) for label,scores in per_emotion_scores.items()}

In [12]:
from tqdm import tqdm
emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label:[] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [11:17<00:00,  7.67it/s]

In [13]:
emotion_scores

{'anger': [0.0641336441040039,
  0.6126197576522827,
  0.0641336441040039,
  0.35148438811302185,
  0.08141235262155533,
  0.2322252243757248,
  0.5381842255592346,
  0.0641336441040039,
  0.3006700277328491,
  0.0641336441040039,
  0.0641336441040039,
  0.611575722694397,
  0.10621576756238937,
  0.0641336441040039,
  0.07239263504743576,
  0.09586360305547714,
  0.16215911507606506,
  0.0641336441040039,
  0.08193837851285934,
  0.22346068918704987,
  0.10715216398239136,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.3963674008846283,
  0.06472679227590561,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.30293282866477966,
  0.06683344393968582,
  0.0641336441040039,
  0.0641336441040039,
  0.1688968539237976,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.07910336554050446,
  0.11856535822153091,
  0.0641336441040039,
  0.5636675953865051,
  0.9171826839447021,
  0.06835687160491943,
  0.2205994576215744,
  0.0641336441040039,
  0.6101735234260559,
  0.07324796915054321,
  0.24804851412773132,
  0.23507270216941833,
  0.0641336441040039,
  0.0641336441040039,
  0.8705508708953857,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.3859492838382721,
  0.592194139957428,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.5385016202926636,
  0.0641336441040039,
  0.0641336441040039,
  0.4989401698112488,
  0.17391566932201385,
  0.0641336441040039,
  0.10230148583650589,
  0.08142109215259552,
  0.0716189369559288,
  0.0641336441040039,
  0.0641336441040039,
  0.12867982685565948,
  0.26979923248291016,
  0.0641336441040039,
  0.8659409284591675,
  0.23667803406715393,
  0.0641336441040039,
  0.007329930551350117,
  0.17137353122234344,
  0.7979862093925476,
  0.019808687269687653,
  0.0641336441040039,
  0.08608242124319077,
  0.09343739598989487,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.24850289523601532,
  0.17442065477371216,
  0.6877568364143372,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.12413683533668518,
  0.007102570030838251,
  0.0641336441040039,
  0.02223181165754795,
  0.15288934111595154,
  0.9578811526298523,
  0.0641336441040039,
  0.272273451089859,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.5306767225265503,
  0.0641336441040039,
  0.07069884240627289,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.8687397241592407,
  0.012943326495587826,
  0.43467190861701965,
  0.3590487837791443,
  0.8035441637039185,
  0.14372120797634125,
  0.5318798422813416,
  0.11999473720788956,
  0.9064609408378601,
  0.13496056199073792,
  0.43805181980133057,
  0.11771012842655182,
  0.7889974117279053,
  0.0641336441040039,
  0.0641336441040039,
  0.1977817565202713,
  0.24558500945568085,
  0.0641336441040039,
  0.0641336441040039,
  0.8385432362556458,
  0.0641336441040039,
  0.3706074059009552,
  0.14360801875591278,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.16254499554634094,
  0.2562013566493988,
  0.5003886222839355,
  0.0641336441040039,
  0.44925200939178467,
  0.0641336441040039,
  0.2738870680332184,
  0.609770655632019,
  0.0641336441040039,
  0.08013715595006943,
  0.2863346040248871,
  0.6032344698905945,
  0.0641336441040039,
  0.0641336441040039,
  0.7178168892860413,
  0.0641336441040039,
  0.2720119059085846,
  0.368863582611084,
  0.7557998299598694,
  0.38339948654174805,
  0.21373745799064636,
  0.0641336441040039,
  0.2838931977748871,
  0.10218366235494614,
  0.5582453608512878,
  0.10218366235494614,
  0.10218366235494614,
  0.0641336441040039,
  0.1614193171262741,
  0.5212736129760742,
  0.0641336441040039,
  0.773124098777771,
  0.0641336441040039,
  0.0641336441040039,
  0.6014090776443481,
  0.4052295386791229,
  0.16290956735610962,
  0.10218366235494614,
  0.08360879868268967,
  0.7985275983810425,
  0.10218366235494614,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.09750133007764816,
  0.09750133007764816,
  0.0641336441040039,
  0.1067848652601242,
  0.10700812935829163,
  0.06517159193754196,
  0.09750133007764816,
  0.5751370787620544,
  0.10218366235494614,
  0.0738193690776825,
  0.4326798915863037,
  0.06425952911376953,
  0.0641336441040039,
  0.2516230344772339,
  0.0641336441040039,
  0.09650137275457382,
  0.0641336441040039,
  0.26266995072364807,
  0.0641336441040039,
  0.3507320284843445,
  0.0641336441040039,
  0.09916401654481888,
  0.4657946228981018,
  0.0641336441040039,
  0.024944432079792023,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.09750133007764816,
  0.06823080778121948,
  0.0641336441040039,
  0.0641336441040039,
  0.152865469455719,
  0.6388862729072571,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.10218366235494614,
  0.37955155968666077,
  0.21778447926044464,
  0.0641336441040039,
  0.03916266933083534,
  0.7949780225753784,
  0.2600882351398468,
  0.0641336441040039,
  0.0641336441040039,
  0.9768814444541931,
  0.6809561848640442,
  0.0641336441040039,
  0.0066813514567911625,
  0.7277459502220154,
  0.48431462049484253,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.26974695920944214,
  0.0641336441040039,
  0.0641336441040039,
  0.22723764181137085,
  0.5407894253730774,
  0.6426545977592468,
  0.0641336441040039,
  0.363709956407547,
  0.12626783549785614,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.031002774834632874,
  0.7438996434211731,
  0.9651405811309814,
  0.10218366235494614,
  0.8991526961326599,
  0.2524696886539459,
  0.0641336441040039,
  0.4709720313549042,
  0.1085946336388588,
  0.0641336441040039,
  0.0641336441040039,
  0.1358344852924347,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.5351661443710327,
  0.13567036390304565,
  0.0641336441040039,
  0.0641336441040039,
  0.008422281593084335,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.08730053156614304,
  0.9571062922477722,
  0.02172883041203022,
  0.7282833456993103,
  0.0641336441040039,
  0.0641336441040039,
  0.38778334856033325,
  0.0641336441040039,
  0.0641336441040039,
  0.9420920610427856,
  0.5118474960327148,
  0.6509760618209839,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.16290956735610962,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.43489307165145874,
  0.23268604278564453,
  0.0641336441040039,
  0.0641336441040039,
  0.3952406048774719,
  0.0641336441040039,
  0.9750319123268127,
  0.2349061518907547,
  0.0641336441040039,
  0.0641336441040039,
  0.5181244611740112,
  0.4451574385166168,
  0.0641336441040039,
  0.12247080355882645,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.5135781764984131,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.008981667459011078,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.4770700931549072,
  0.8954954147338867,
  0.0641336441040039,
  0.0861862301826477,
  0.01330319419503212,
  0.9142308235168457,
  0.0641336441040039,
  0.4976477324962616,
  0.0641336441040039,
  0.024999016895890236,
  0.112225741147995,
  0.969167947769165,
  0.9688320159912109,
  0.2806225121021271,
  0.0641336441040039,
  0.6925894021987915,
  0.0641336441040039,
  0.2092653065919876,
  0.0641336441040039,
  0.029818836599588394,
  0.905593752861023,
  0.15540051460266113,
  0.0641336441040039,
  0.0641336441040039,
  0.3370526134967804,
  0.7603247165679932,
  0.0641336441040039,
  0.11497801542282104,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.32776543498039246,
  0.2919781804084778,
  0.09479234367609024,
  0.13449637591838837,
  0.0641336441040039,
  0.3932490944862366,
  0.3680073618888855,
  0.9660278558731079,
  0.0641336441040039,
  0.8328171372413635,
  0.0641336441040039,
  0.7876132726669312,
  0.0641336441040039,
  0.07499007880687714,
  0.0641336441040039,
  0.20969152450561523,
  0.0641336441040039,
  0.1351090669631958,
  0.6616066694259644,
  0.09750133007764816,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.6454071402549744,
  0.0641336441040039,
  0.0641336441040039,
  0.06575880944728851,
  0.1327088475227356,
  0.0641336441040039,
  0.07423651963472366,
  0.0641336441040039,
  0.09550858289003372,
  0.017479754984378815,
  0.12716443836688995,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.8705232739448547,
  0.5779547691345215,
  0.10024647414684296,
  0.2826181948184967,
  0.0641336441040039,
  0.0641336441040039,
  0.09961843490600586,
  0.0641336441040039,
  0.6838445663452148,
  0.0641336441040039,
  0.0641336441040039,
  0.17344936728477478,
  0.23477040231227875,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.00792578887194395,
  0.0641336441040039,
  0.0641336441040039,
  0.12187694013118744,
  0.0641336441040039,
  0.15642231702804565,
  0.0641336441040039,
  0.0641336441040039,
  0.6875433325767517,
  0.4950047433376312,
  0.0641336441040039,
  0.4046885669231415,
  0.0641336441040039,
  0.4907580614089966,
  0.0641336441040039,
  0.014079447835683823,
  0.01628262922167778,
  0.9380816221237183,
  0.05437515303492546,
  0.004618237726390362,
  0.1739843338727951,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0863659456372261,
  0.0641336441040039,
  0.9789203405380249,
  0.09161905199289322,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.23588360846042633,
  0.270315021276474,
  0.036636918783187866,
  0.0641336441040039,
  0.10823167115449905,
  0.0641336441040039,
  0.11946296691894531,
  0.20517322421073914,
  0.7506119608879089,
  0.21108388900756836,
  0.3228694200515747,
  0.24379827082157135,
  0.0641336441040039,
  0.27691107988357544,
  0.18406297266483307,
  0.19377246499061584,
  0.4385436773300171,
  0.11380310356616974,
  0.9838340878486633,
  0.07747047394514084,
  0.3837374150753021,
  0.6569238901138306,
  0.09617386013269424,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.3283517360687256,
  0.2503569722175598,
  0.0641336441040039,
  0.28113606572151184,
  0.11742161959409714,
  0.25321337580680847,
  0.0511343777179718,
  0.0641336441040039,
  0.0641336441040039,
  0.76947420835495,
  0.0641336441040039,
  0.01621435210108757,
  0.0641336441040039,
  0.0641336441040039,
  0.14795425534248352,
  0.10218366235494614,
  0.29012197256088257,
  0.9472188353538513,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.3016374707221985,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0009619180345907807,
  0.2212262898683548,
  0.0641336441040039,
  0.15158061683177948,
  0.940525472164154,
  0.0641336441040039,
  0.6997010111808777,
  0.3579035997390747,
  0.6533927321434021,
  0.21454502642154694,
  0.23236069083213806,
  0.0641336441040039,
  0.09768054634332657,
  0.0641336441040039,
  0.10113592445850372,
  0.0641336441040039,
  0.4171808362007141,
  0.0641336441040039,
  0.39303112030029297,
  0.04374377802014351,
  0.023972468450665474,
  0.6371719837188721,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.10218366235494614,
  0.11871591210365295,
  0.8641870021820068,
  0.19327710568904877,
  0.2643408477306366,
  0.3057028651237488,
  0.0641336441040039,
  0.1856222152709961,
  0.004436873365193605,
  0.0641336441040039,
  0.0641336441040039,
  0.5747718811035156,
  0.0641336441040039,
  0.0641336441040039,
  0.08672020584344864,
  0.0641336441040039,
  0.0641336441040039,
  0.2632944881916046,
  0.0656520202755928,
  0.0641336441040039,
  0.27912336587905884,
  0.0641336441040039,
  0.10218366235494614,
  0.04338757321238518,
  0.0641336441040039,
  0.0641336441040039,
  0.8541301488876343,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0035886031109839678,
  0.0641336441040039,
  0.0641336441040039,
  0.10218366235494614,
  0.004467179533094168,
  0.0943569764494896,
  0.9339855313301086,
  0.8516484498977661,
  0.07177876681089401,
  0.0641336441040039,
  0.0641336441040039,
  0.06571821868419647,
  0.07647926360368729,
  0.023972468450665474,
  0.08836571872234344,
  0.1408153474330902,
  0.0641336441040039,
  0.8200718760490417,
  0.0641336441040039,
  0.0641336441040039,
  0.09904078394174576,
  0.0718848928809166,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.07387750595808029,
  0.0641336441040039,
  0.05249432846903801,
  0.0641336441040039,
  0.0641336441040039,
  0.01144117210060358,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.17408165335655212,
  0.0641336441040039,
  0.0641336441040039,
  0.4684460163116455,
  0.94921875,
  0.0641336441040039,
  0.005524298641830683,
  0.893893837928772,
  0.0641336441040039,
  0.0641336441040039,
  0.9226340055465698,
  0.4383928179740906,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.19669756293296814,
  0.757264256477356,
  0.0641336441040039,
  0.0641336441040039,
  0.024205287918448448,
  0.0641336441040039,
  0.019731411710381508,
  0.0641336441040039,
  0.031440865248441696,
  0.0641336441040039,
  0.6565325260162354,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.07220085710287094,
  0.0641336441040039,
  0.029801903292536736,
  0.11216066032648087,
  0.0641336441040039,
  0.0641336441040039,
  0.09086902439594269,
  0.0641336441040039,
  0.0641336441040039,
  0.08249074965715408,
  0.0641336441040039,
  0.0641336441040039,
  0.3090108633041382,
  0.0641336441040039,
  0.1682567000389099,
  0.0641336441040039,
  0.7006731629371643,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.9646543264389038,
  0.7201752662658691,
  0.8552455306053162,
  0.9343000054359436,
  0.6406770348548889,
  0.4510978162288666,
  0.0641336441040039,
  0.8243371248245239,
  0.0641336441040039,
  0.9458311796188354,
  0.53360515832901,
  0.0641336441040039,
  0.828179657459259,
  0.0641336441040039,
  0.0641336441040039,
  0.8798778057098389,
  0.012997053563594818,
  0.04755372181534767,
  0.006497412454336882,
  0.0641336441040039,
  0.1963806450366974,
  0.13231563568115234,
  0.11823950707912445,
  0.06946374475955963,
  0.0641336441040039,
  0.0641336441040039,
  0.06687138229608536,
  0.4853964149951935,
  0.0641336441040039,
  0.13322004675865173,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0659358948469162,
  0.0641336441040039,
  0.5315346717834473,
  0.10201448202133179,
  0.5181265473365784,
  0.0641336441040039,
  0.0013625039719045162,
  0.0641336441040039,
  0.40271902084350586,
  0.0641336441040039,
  0.09669872373342514,
  0.3286033570766449,
  0.0641336441040039,
  0.0641336441040039,
  0.6208807826042175,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.008911808021366596,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.1724746972322464,
  0.0641336441040039,
  0.03281401842832565,
  0.0641336441040039,
  0.1767178475856781,
  0.020691022276878357,
  0.0641336441040039,
  0.10218366235494614,
  0.15795177221298218,
  0.0641336441040039,
  0.24458155035972595,
  0.25616690516471863,
  0.7802669405937195,
  0.18948835134506226,
  0.0641336441040039,
  0.0641336441040039,
  0.10218366235494614,
  0.041422754526138306,
  0.0641336441040039,
  0.2104586958885193,
  0.10899484902620316,
  0.01468261331319809,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.2237055003643036,
  0.0641336441040039,
  0.0666525661945343,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.10546308755874634,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.8686034083366394,
  0.9057343602180481,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.17697438597679138,
  0.3499116897583008,
  0.0641336441040039,
  0.0641336441040039,
  0.3657284379005432,
  0.20955078303813934,
  0.0641336441040039,
  0.14985054731369019,
  0.20651228725910187,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.9297389984130859,
  0.06650443375110626,
  0.0641336441040039,
  0.10228950530290604,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.6387801766395569,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.4687056541442871,
  0.0641336441040039,
  0.0641336441040039,
  0.10296017676591873,
  0.793667197227478,
  0.0641336441040039,
  0.6943923234939575,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.07193180173635483,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.1362968534231186,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.14197894930839539,
  0.0641336441040039,
  0.0641336441040039,
  0.2212371975183487,
  0.08981611579656601,
  0.42355674505233765,
  0.08037097752094269,
  0.0641336441040039,
  0.0641336441040039,
  0.18543066084384918,
  0.9205765128135681,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.25224044919013977,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.9673675298690796,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.10402043908834457,
  0.0641336441040039,
  0.28318431973457336,
  0.12954866886138916,
  0.0641336441040039,
  0.27020347118377686,
  0.0755019336938858,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.3632236421108246,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.06473162025213242,
  0.0641336441040039,
  0.8917672038078308,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.09424413740634918,
  0.0641336441040039,
  0.010542131029069424,
  0.0641336441040039,
  0.09372229129076004,
  0.1260547637939453,
  0.0641336441040039,
  0.6531062722206116,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.0641336441040039,
  0.09283570200204849,
  0.03924131765961647,
  0.0641336441040039,
  0.020597631111741066,
  0.4206746816635132,
  0.43685224652290344,
  0.0641336441040039,

In [14]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [15]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273592,0.928168,0.932798,0.646216,0.967158,0.729602,9780002005883
1,0.612620,0.348285,0.942528,0.704422,0.887940,0.111690,0.252546,9780002261982
2,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078766,9780006178736
3,0.351484,0.150722,0.360706,0.251881,0.732684,0.111690,0.078766,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078766,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148208,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400262,0.883198,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459269,0.759456,0.951104,0.368111,0.078766,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059

In [16]:
books = pd.merge(books,emotions_df,on="isbn13")

In [17]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273592,0.928168,0.932798,0.646216,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887940,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078766
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NonFiction,0.351484,0.150722,0.360706,0.251881,0.732684,0.111690,0.078766
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NonFiction,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078766

In [18]:
books.to_csv("books_with_emotions.csv",index = False)